name: Java CI Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Set up JDK 17
      uses: actions/setup-java@v2.3.1
      with:
        java-version: 17
        distribution: zulu

    # Determine next version to build. New version is in variable new_tag
    - name: Determine new version
      id: versioning
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: kevinferrare
        RELEASE_BRANCHES: main
        INITIAL_VERSION: 1.0.0
        DRY_RUN: false

    # Sets the versions in the pom so that the generated artifacts are not -SNAPSHOT, build and publish
    - name: Build Maven
      env:
        VERSION: ${{ steps.versioning.outputs.new_tag }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mvn -B versions:set -DnewVersion=${VERSION} &> /dev/null
        mvn -B clean install
        mvn -B deploy